export const BACKGROUNDS: Record<string, string[]> = {
  IPL: [
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh2.jpg",
    "/images/backgrounds/srh3.jpg",
    "/images/backgrounds/srh4.jpg",
    "/images/backgrounds/srh5.jpg",
    "/images/backgrounds/csk1.jpg",
    "/images/backgrounds/rcb1.jpg",
    "/images/backgrounds/rcb2.jpg",
    "/images/backgrounds/rcb3.jpg",
    "/images/backgrounds/mi1.jpg",
    "/images/backgrounds/kkr1.jpg",
    "/images/backgrounds/kkr2.jpg",
    "/images/backgrounds/dc1.jpg",
    "/images/backgrounds/dc2.jpg",
    "/images/backgrounds/rr1.jpg",
    "/images/backgrounds/rr2.jpg",
    "/images/backgrounds/pbks1.jpg",
    "/images/backgrounds/gt1.jpg",
  ],
};
