export const BACKGROUNDS: Record<string, string[]> = {
  SRH: [
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
    "/images/backgrounds/srh1.jpg",
  ],
  CSK: [],
  MI: [],
  RCB: [],
  KKR: [],
  RR: [],
  DC: [],
  PBKS: [],
  LSG: [],
  GT: [],
};
